Repository SIGMA-LA/Front-End-SIGMA-LA, pull requests merged in 2025-09, with the labels that each got.

#2 chore: Set up templates
  .github/ISSUE_TEMPLATE/🐞-reporte-de-bug.md
  .github/ISSUE_TEMPLATE/🚀-nueva-funcionalidad.md
Labels: type: chore, pr: ready-for-review

#19 fix: Fixed the coordinacion dashboard implementation
  src/app/coordinacionDashboard/layout.tsx
  src/app/coordinacionDashboard/page.tsx
  src/app/login/page.tsx
  src/components/ClientesList.tsx
  src/components/Configuraciones.tsx
  src/components/CrearCliente.tsx
  src/components/CrearEntrega.tsx
  src/components/CrearObra.tsx
  src/components/CrearVisita.tsx
  src/components/DashboardSwitcher.tsx
  src/components/EntregasList.tsx
  src/components/LoginForm.tsx
  src/components/ObrasList.tsx
  src/components/VisitaDetails.tsx
  src/components/VisitasList.tsx
  src/components/features/coordinacionDashboard/CoordDashboardClient.tsx
  src/components/features/encargadoDashboard/EncargadoDashboardClient.tsx
  src/components/features/visitadorDashboard/VisitadorDashboard.tsx
  src/components/layout/Navbar.tsx
  src/data/mockData.ts
  src/types/index.ts
Labels: priority: critical, module: ui-ux, pr: ready-for-review

#20 Feature: Reorganization of the folders and archives structure
  pnpm-lock.yaml
  postcss.config.mjs
  src/app/adminDashboard/layout.tsx
  src/app/adminDashboard/page.tsx
  src/app/coordinacionDashboard/page.tsx
  src/app/dashboard/_components/admin/AdminDashboardClient.tsx
  src/app/dashboard/_components/coordinacion/ClientesList.tsx
  src/app/dashboard/_components/coordinacion/Configuraciones.tsx
  src/app/dashboard/_components/coordinacion/CoordDashboardClient.tsx
  src/app/dashboard/_components/coordinacion/CrearCliente.tsx
  src/app/dashboard/_components/coordinacion/CrearEntrega.tsx
  src/app/dashboard/_components/coordinacion/CrearObra.tsx
  src/app/dashboard/_components/coordinacion/CrearVisita.tsx
  src/app/dashboard/_components/coordinacion/EntregasList.tsx
  src/app/dashboard/_components/coordinacion/ObrasList.tsx
  src/app/dashboard/_components/coordinacion/VisitaDetails.tsx
  src/app/dashboard/_components/coordinacion/VisitasList.tsx
  src/app/dashboard/_components/encargado/EncargadoDashboardClient.tsx
  src/app/dashboard/_components/visitador/VisitadorDashboard.tsx
  src/app/dashboard/layout.tsx
  src/app/dashboard/page.tsx
  src/app/encargadoDashboard/layout.tsx
  src/app/encargadoDashboard/page.tsx
  src/app/globals.css
  src/app/layout.tsx
  src/app/login/_components/LoginForm.tsx
  src/app/login/page.tsx
  src/app/page.tsx
  src/app/visitadorDashboard/layout.tsx
  src/app/visitadorDashboard/page.tsx
  src/components/ClientesList.tsx
  src/components/Configuraciones.tsx
  src/components/CrearCliente.tsx
  src/components/CrearObra.tsx
  src/components/CrearVisita.tsx
  src/components/EntregasList.tsx
  src/components/LoginForm.tsx
  src/components/ObrasList.tsx
  src/components/VisitaDetails.tsx
  src/components/VisitasList.tsx
  src/components/features/adminDashboard/AdminDashboardClient.tsx
  src/components/features/coordinacionDashboard/CoordDashboardClient.tsx
  src/components/features/encargadoDashboard/EncargadoDashboardClient.tsx
  src/components/features/visitadorDashboard/VisitadorDashboard.tsx
  src/components/layout/Navbar.tsx
  src/components/ui/Button.tsx
  src/components/ui/Card.tsx
  src/components/ui/Input.tsx
  src/components/ui/Label.tsx
  src/components/ui/Textarea.tsx
  src/context/AuthContext.tsx
  src/context/GlobalContext.tsx
  src/data/mockData.ts
  src/schemas/loginSchemas.ts
  src/types/index.ts
  tailwind.config.ts
  tsconfig.json
Labels: type: chore, priority: critical, module: auth, module: ui-ux, pr: ready-for-review
