Repository SIGMA-LA/Front-End-SIGMA-LA, pull requests merged in 2025-10, with the labels that each got.

#45 Feature: Crud Presupuesto and Create Obras
  package.json
  pnpm-lock.yaml
  src/app/dashboard/_components/admin/AdminDashboardClient.tsx
  src/app/dashboard/_components/admin/DashboardView.tsx
  src/app/dashboard/_components/admin/EmpleadosView.tsx
  src/app/dashboard/_components/admin/ObrasView.tsx
  src/app/dashboard/_components/admin/ReportesView.tsx
  src/app/dashboard/_components/coordinacion/CrearEntrega.tsx
  src/app/dashboard/_components/coordinacion/MaquinariaList.tsx
  src/app/dashboard/_components/coordinacion/VehiculosList.tsx
  src/app/dashboard/_components/coordinacion/VisitaDetails.tsx
  src/app/dashboard/_components/shared/EntregasList.tsx
  src/app/dashboard/_components/shared/EstadoObraBadge.tsx
  src/app/dashboard/_components/shared/ObrasList.tsx
  src/app/dashboard/_components/ventas/CrearCliente.tsx
  src/app/dashboard/_components/ventas/CrearObra.tsx
  src/app/dashboard/_components/ventas/CrearPresupuestoModal.tsx
  src/app/dashboard/_components/ventas/VentasDashboard.tsx
  src/components/layout/Navbar.tsx
  src/context/GlobalContext.tsx
  src/services/cliente.service.ts
  src/services/empleado.service.ts
  src/services/entregas.service.ts
  src/services/obra.service.ts
  src/services/presupuesto.service.ts
  src/types/index.ts
Labels: type: feature, module: ui-ux

#51 Feature: Entrega crud integration
  src/app/dashboard/_components/coordinacion/CrearEntrega.tsx
  src/app/dashboard/_components/shared/AsignarPersonalModal.tsx
  src/app/dashboard/_components/shared/EntregaDetailsModal.tsx
  src/app/dashboard/_components/shared/EntregasList.tsx
  src/app/dashboard/_components/shared/SelectionModal.tsx
  src/services/empleado.service.ts
  src/services/entregas.service.ts
  src/services/parametro.service.ts
  src/types/index.ts
Labels: type: feature

#54 Feature/refactor maquinaria system
  src/actions/maquinarias.ts
  src/app/dashboard/_components/coordinacion/CambiarEstadoModal.tsx
  src/app/dashboard/_components/coordinacion/ConfirmDeleteModal.tsx
  src/app/dashboard/_components/coordinacion/CoordDashboardClient.tsx
  src/app/dashboard/_components/coordinacion/CrearMaquinaria.tsx
  src/app/dashboard/_components/coordinacion/DetalleMaquinaria.tsx
  src/app/dashboard/_components/coordinacion/EditarMaquinaria.tsx
  src/app/dashboard/_components/coordinacion/MaquinariaList.tsx
  src/app/dashboard/_components/coordinacion/maquinaria/ConfirmDeleteMaquinariaModal.tsx
  src/app/dashboard/_components/coordinacion/maquinaria/CrearMaquinariaModal.tsx
  src/app/dashboard/_components/coordinacion/maquinaria/EditarMaquinariaModal.tsx
  src/app/dashboard/_components/coordinacion/maquinaria/MaquinariaCard.tsx
  src/app/dashboard/_components/coordinacion/maquinaria/MaquinariaList.tsx
  src/app/dashboard/_components/coordinacion/maquinaria/VerDetallesMaquinariaModal.tsx
  src/context/AuthContext.tsx
  src/services/maquinaria.service.ts
  src/types/index.ts
Labels: module: ui-ux, pr: ready-for-review

#58 Feat: Implementacion de usos maquinaria y Orden de Producción en entrega
  src/app/dashboard/_components/coordinacion/CrearEntrega.tsx
  src/app/dashboard/_components/produccion/OrdenProduccionCard.tsx
  src/app/dashboard/_components/shared/EntregaDetailsModal.tsx
  src/app/dashboard/_components/shared/SelectionModal.tsx
  src/services/entregas.service.ts
  src/services/maquinaria.service.ts
  src/types/index.ts
Labels: type: feature

#60 feat: Mejora la UX en los flujos de Obra, Pagos y Entregas
  src/app/dashboard/_components/admin/DashboardView.tsx
  src/app/dashboard/_components/planta/FinalizarEntregaModal.tsx
  src/app/dashboard/_components/planta/PlantaDashboardClient.tsx
  src/app/dashboard/_components/produccion/NotaFabricaDetails.tsx
  src/app/dashboard/_components/shared/EstadoObraBadge.tsx
  src/app/dashboard/_components/shared/ObrasList.tsx
  src/app/dashboard/_components/ventas/CrearObra.tsx
  src/app/dashboard/_components/visitador/VisitadorDashboard.tsx
  src/services/entregas.service.ts
  src/services/obra.service.ts
  src/services/visitas.service.ts
  src/types/index.ts
Labels: type: feature, module: database, module: api, pr: ready-for-review
